version: 2

models:
  - name: stg_addresses
    description: Addresses of users
    columns:
      - name: address_id
        description: Id for each unique address
        tests: 
          - not_null
          - unique
      - name: address
        description: First line of address
      - name: zipcode
        description: Zipcode of address
      - name: state
        description: State code for address
        test: 
          - not_null
      - name: country
 
  - name: stg_events
    description: List of events
    columns:
      - name: event_id
        description: UUI for each unique event
        tests: 
          - not_null
          - unique
      - name: session_id
      - name: user_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id
      - name: page_url
      - name: created_at
      - name: event_type
      - name: order_id
      - name: product_id

  - name: stg_order_items
    description: table of items that can be or have been ordered
    columns:
      - name: quantity
      - name: order_id
        tests: 
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id

  - name: stg_orders
    description: Orders made by users
    columns:
    - name: order_id
      description: UUID for orders
      tests:
        - not_null
        - unique
    - name: user_id
      description: user id for order
      tests:
        - not_null
        - relationships:
            to: ref('stg_users')
            field: user_id
    - name: promo_id
    - name: address_id
    - name: created_at
    - name: order_cost
    - name: shipping_cost
    - name: order_total
    - name: tracking_id
    - name: shipping_service
    - name: estimated_delivery_at
    - name: delivered_at
    - name: status

  - name: stg_products
    description: list of products
    columns:
      - name: price
        tests:
          - positive_values
          - not_null
      - name: inventory
        tests: 
          - not_null
          - positive_values
      - name: product_id
        tests:
          - not_null
          - unique
      - name: name
  
  - name: stg_promos
    description: table of promotions
    columns:
      - name: promo_id
        description: UUID for promotions
        tests: 
          - not_null
          - unique
      - name: promo_status
      - name: promo_discount

  - name: stg_users
    description: Users and information about users
    columns:
      - name: user_id
        description: UUID for each unique user
        tests: 
          - not_null
          - unique
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: user_created_at
      - name: user_updated_at
      - name: address_id